---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: simpl-os
description: Simplest OS ever

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      # Office
      - libreoffice
      # Media
      - ffmpeg
      - gimp
      - okular
      - vlc
      # System
      - btop
      - fastfetch
      - kate
      - steam-devices
    remove:
      - nvtop
      - htop

  - type: default-flatpaks
    configurations:
      - scope: system
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
          title: Flathub


  - type: signing
